---
- hosts: scaleway-docker
  remote_user: root
  tasks:
    - name: apt-get upgrade
      shell: apt-get -y upgrade
    - name: install apt-transport-https
      apt:
        name: apt-transport-https
        update_cache: yes
    - name: install ca-certificates
      apt:
        name: ca-certificates
    - name: Add docker apt keys
      # apt_key: keyserver=keyserver.ubuntu.com id=36A1D7869245C8950F966E92D8576A8BA88D21E9
      apt_key: 
        keyserver: hkp://p80.pool.sks-keyservers.net:80
        id: 58118E89F3A912897C070ADBF76221572C52609D

    - name: add docker apt repository
      apt_repository:
        repo: deb https://apt.dockerproject.org/repo ubuntu-trusty main
        update_cache: yes

    # - name: Write docker.list
    #   copy: src=docker.list dest=/etc/apt/sources.list.d/docker.list

    - name: purge lxc-docker
      apt:
        name: lxc-docker
        state: absent
        purge: yes
        update_cache: yes

    # - name: install linux-image-extra-$(uname -r)
    #   shell: apt-get install linux-image-extra-$(uname -r)
      # apt:
      #   name: linux-image-extra-$(uname -r)
      #   update_cache: yes

    - name: install linux-image-extra-virtual
      apt:
        name: linux-image-extra-virtual
        update_cache: yes

    - name: install docker
      apt:
        name: docker-engine
        update_cache: yes

    - name: start docker
      service:
        name: docker
        state: started
